# Exercise 1 

In [45]:
import numpy as np

In [46]:
cost_price = np.array([1500,3000,5000])

daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

print("Shape of Cost_price: ",cost_price.shape)
print("Dimentions of cost_orice: ",cost_price.ndim)

print(daily_sales.shape)
print(daily_sales.ndim)


Shape of Cost_price:  (3,)
Dimentions of cost_orice:  1
(3, 4)
2


In [47]:
#adding 2 to the array
daily_sales+=2

In [48]:
#calculating revenue
revenue = cost_price.reshape(3,1) * daily_sales
print(revenue)

[[18000 25500 15000 21000]
 [21000 27000 18000 24000]
 [20000 25000 20000 30000]]


In [49]:
#Sales data for Smartwatches for all asssuming row 1 is data for Smartwatches 
print("Sales data for Smartwatches: ",revenue[1])

Sales data for Smartwatches:  [21000 27000 18000 24000]


In [50]:
#print data for 1st 2 days 
print(revenue[0:2])

[[18000 25500 15000 21000]
 [21000 27000 18000 24000]]


In [51]:
#data for sepakers sales on THRUSDAY
print("Revenue generated by sepaker sales on Thrusday: ",revenue[2][3])


Revenue generated by sepaker sales on Thrusday:  30000


In [52]:
#converting daily_sales arrray to 1d 
daily_sales.reshape(12,)


array([12, 17, 10, 14,  7,  9,  6,  8,  4,  5,  4,  6])

In [53]:
daily_sales = daily_sales.reshape(2,6)
print(daily_sales)

[[12 17 10 14  7  9]
 [ 6  8  4  5  4  6]]


In [54]:
discount_per = np.linspace(0,100,10)
print(discount_per)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [55]:
pridicted_sales = np.random.randint(0, 20, size=(3, 4))
print(pridicted_sales)

[[ 5 12 17  9]
 [ 9  2 10 10]
 [11  4 14  9]]


In [56]:
random_arr = np.random.rand(5)
print(random_arr)

[0.01997875 0.35910956 0.5428966  0.10123726 0.64343612]


In [57]:
#print sum of all items sold
total_item_sold = np.sum(daily_sales)
print(total_item_sold)

102


In [58]:
#printing total item sold for each product

print("Toal Headphones sold: ",daily_sales.reshape(3,4)[0].sum())

Toal Headphones sold:  53


# Excercise 2

In [59]:
import numpy as np

In [60]:
student_data = np.array([[78,85,90],
                         [45,60,55],
                         [88,92,95],
                         [30,40,35],
                         [65,70,75]])
print(student_data)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [61]:
print("Shape of student_data : ",student_data.shape)
print("Total Number of elements : ",student_data.size)
print("Data types  of elements : ",student_data.dtype)


Shape of student_data :  (5, 3)
Total Number of elements :  15
Data types  of elements :  int64


In [62]:
print("marks of 2nd student: ",student_data[1])
print("\n")
print("marks of 1st student in 3rd subject: ",student_data[0][2])
print("marks of 2nd student in 3rd subject: ",student_data[1][2])
print("marks of 3rd student in 3rd subject: ",student_data[2][2])
print("marks of 4th student in 3rd subject: ",student_data[3][2])
print("marks of 5th student in 3rd subject: ",student_data[4][2])
print("\n")
print("marks of 1st student in 2nd subject: ",student_data[0][1])


marks of 2nd student:  [45 60 55]


marks of 1st student in 3rd subject:  90
marks of 2nd student in 3rd subject:  55
marks of 3rd student in 3rd subject:  95
marks of 4th student in 3rd subject:  35
marks of 5th student in 3rd subject:  75


marks of 1st student in 2nd subject:  85


In [63]:
#MEANS AND AVERAGES
subject_mean = np.mean(student_data, axis=0)
print("Mean of all subjects : ",subject_mean)

avg_marks = np.average(student_data, axis=0)
print("Average of all subjects : ",avg_marks)


Mean of all subjects :  [61.2 69.4 70. ]
Average of all subjects :  [61.2 69.4 70. ]


In [64]:
#filtering Top performers 
result = student_data[student_data >= 80]
print("marks scored above 80 : ",result)



marks scored above 80 :  [85 90 88 92 95]


In [65]:
student_data+=5
print(student_data)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]


In [66]:
status = np.where(student_data>=50,1,0)
print(status)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [0 0 0]
 [1 1 1]]


In [67]:
student_data = np.where(student_data<50,0,student_data)
print(student_data)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [  0   0   0]
 [ 70  75  80]]


In [68]:
avg = np.average(student_data,axis=1)
grades = np.where(avg >= 85, 10,
         np.where(avg >= 70, 8,
         np.where(avg >= 50, 6, 0)))
print(grades)


[10  6 10  0  8]


In [69]:
backup = student_data.copy()

student_data[0, 0] = 0

print("Original Marks:\n", student_data)
print("Backup Marks:\n", backup)

Original Marks:
 [[  0  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [  0   0   0]
 [ 70  75  80]]
Backup Marks:
 [[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [  0   0   0]
 [ 70  75  80]]
